[package]
name = "sc2-bevy"
description = "Bevy plugin: StarCraft II units (simulated by sc2-api) living in the San Andreas world"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
sc2-api = { path = "../sc2-api" }
sc2-formats = { path = "../sc2-formats" }
anyhow.workspace = true
bevy.workspace = true
sa-physics = { path = "../sa-physics", features = ["bevy"] }

[features]
default = ["dev"]
dev = ["bevy/dynamic_linking"]
